#!/bin/sh
set -e

# Export the default variables
set -a
. "${REDIS_CONFIG_DIR}/defaults.env"
set +a

# Substitute variables in the template
CONTENT=$(envsubst < "${REDIS_CONFIG_DIR}/sentinel.conf")

# Save the updated config file
TARGET_CONFIG=${REDIS_CONFIG_FILE:-"/data/sentinel.conf"}
if [ -f "$TARGET_CONFIG" ]; then
  # Keep any data previously generated by Redis Sentinel
  GENERATED=$(awk '/# Generated by CONFIG REWRITE/,0' "$TARGET_CONFIG")
  printf '%s\n\n%s\n' "$CONTENT" "$GENERATED" > "$TARGET_CONFIG"
else
  printf '%s\n' "$CONTENT" > "$TARGET_CONFIG"
fi

# Remove config lines for empty password
if [ -z "$REDIS_SENTINEL_PASSWORD" ]; then
  sed -i '/^requirepass /d' "$TARGET_CONFIG"
fi

# Remove config lines for empty primary password
if [ -z "$REDIS_PRIMARY_PASSWORD" ]; then
  sed -i '/^sentinel auth-pass /d' "$TARGET_CONFIG"
  sed -i '/^sentinel auth-user /d' "$TARGET_CONFIG"
fi

# Run Redis as a sentinel instance
echo "${TARGET_CONFIG}:" && cat "$TARGET_CONFIG"
exec redis-server "$TARGET_CONFIG" --port "${REDIS_SENTINEL_PORT:-26379}" \
  --sentinel "$@"
